# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task -l

  submodules:init:
    desc: Initialize and update git submodules
    cmds:
      - git submodule update --init --recursive
  
  git:commit-push:
    desc: 'Commit all changes and push (usage: go-task git:commit-push -- "message")'
    vars:
      MSG: '{{.CLI_ARGS}}'
    preconditions:
      - sh: '[ -n "{{.MSG}}" ]'
        msg: "Commit message required. Usage: task git:commit-push -- \"message\""
    cmds:
      - git add -A
      - git commit -m "{{.MSG}}"
      - git push

  mcp:run:
    desc: Run MCP server
    dir: ./mcp
    cmds:
      - go run ./cmd/mcp

  mcp:build:
    desc: Build MCP binary
    dir: ./mcp
    cmds:
      - go build -o ./target/SurferMcp ./cmd/mcp

  ext:dev:
    desc: Run extension dev server
    dir: ./extension
    cmds:
      - pnpm install
      - pnpm dev
